### ISSUE TITLE
Nix flake for mac

### ISSUE THREAD

**Issue by daviewales** [onekey-sec/unblob#494]
The nix flake doesn't appear to support mac.
I'm getting the following error when following the installation instructions on the website:

```
❯ cat > ~/.config/nix/nix.conf <<EOF
experimental-features = nix-command flakes
EOF

❯ cat ~/.config/nix/nix.conf
experimental-features = nix-command flakes
❯ nix-env -iA cachix -f https://cachix.org/api/v1/install
cachix use unblob

installing 'cachix-1.2'
Configured https://unblob.cachix.org binary cache in /Users/dwales/.config/nix/nix.conf
❯ nix profile install github:onekey-sec/unblob

error: flake 'github:onekey-sec/unblob' does not provide attribute 'packages.x86_64-darwin.default' or 'defaultPackage.x86_64-darwin'
```

I'm no nix expert, but I wonder if this is because `system` is hardcoded to "x86_64-linux" in [flake.nix](https://github.com/onekey-sec/unblob/blob/main/flake.nix).

[Nix By Example](https://mimoo.github.io/nixbyexample/basics-hello-world.html) suggests replacing `linux` with `darwin`, so I might fork and try that.

**Comment by daviewales** [comment]
Hmm... I just tried swapping the hard-coded `linux` value for a hard-coded `darwin` value; it gets further, then fails with:

```
❯ nix profile install github:daviewales/unblob
error: Package ‘glibc-2.35-163’ in /nix/store/qxdnmb9fv3n122n06qx79zm0mbm37q99-source/pkgs/development/libraries/glibc/default.nix:152 is not supported on ‘x86_64-darwin’, refusing to evaluate.
```

I wonder if it's possible to make that conditional, and use the built-in libc on macOS.

**Comment by vlaci** [comment]
I would be glad to have Mac supported.

Would applying this change unblock you?

```diff --git a/default.nix b/default.nix
index 49c7c49..a93a2e5 100644
--- a/default.nix
+++ b/default.nix
@@ -80,7 +80,6 @@ let
 
     postFixup = ''
       wrapProgram $out/bin/unblob --prefix PATH : ${lib.makeBinPath runtimeDeps} \
-                                  --set LOCALE_ARCHIVE_2_27 ${glibc}/lib/locale/locale-archive \
                                   --set LC_ALL C.UTF-8
     '';
 
```

This is there to make unblob work on ancient distros, definitely can change it to be conditional.

**Comment by daviewales** [comment]
We get a lot further with that change!

I get these errors now:

```
❯ nix profile install .
warning: Git tree '/Users/dwales/Code/not-my-code/unblob' is dirty
warning: could not update mtime for file '/Users/dwales/.cache/nix/gitv3/16nf2grplv1dlhr7alpd928p2wkvkp651wkicy34wf7sa7da2l43/refs/heads/HEAD': No such file or directory
warning: could not update mtime for file '/Users/dwales/.cache/nix/gitv3/12g7kxi0vm1m1pcqn8diw0k41piqi88pcnbyifjqw6llxm81as6b/refs/heads/HEAD': No such file or directory
warning: could not update mtime for file '/Users/dwales/.cache/nix/gitv3/1vajyj0qzk2vchk7hvhs778i38aimbhm2dnjy6iarxh5nbpqddbz/refs/heads/HEAD': No such file or directory
error: builder for '/nix/store/cb3ygx1ri62ckrqk7i741qd1az3g52ff-python3.10-lief-0.12.3.drv' failed with exit code 2;
       last 10 log lines:
       >   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
       >   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
       > ModuleNotFoundError: No module named 'setuptools'
       >
       >
       For full logs, run 'nix log /nix/store/cb3ygx1ri62ckrqk7i741qd1az3g52ff-python3.10-lief-0.12.3.drv'.
error: 1 dependencies of derivation '/nix/store/0b50asnvcgp1dyid408vdwzcnzy5avmz-python3.10-unblob-0.1.0.drv' failed to build
```

I'm wondering if that's an upstream issue?

<details>

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/6j0kq3a4zn18ra9s62dgkz1ziyyain3r-lief-0.12.3.zip
source root is lief-0.12.3
setting SOURCE_DATE_EPOCH to timestamp 1667325146 of file lief-0.12.3/setup.cfg
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing pipBuildPhase
Creating a wheel...
[33mWARNING: The directory '/homeless-shelter/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.[0m[33m
[0mProcessing /private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/lief-0.12.3
  Running command Preparing metadata (pyproject.toml)
  Preparing metadata (pyproject.toml) ... [?25l[?25hdone
[31mERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/commands/wheel.py", line 145, in run
    requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 68, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 533, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 706, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 188, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/nix/store/qlhqfiknrp0ysf5qp4g9524c6wsiy57s-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/nix/store/hp8vf91s8z2gljwdrf0i4jry8m3899m7-python3-3.10.7/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'
[0m[31m
[0m
```

</details>

**Comment by vlaci** [comment]
Ugh, lief doesn't have a wheel for darwin.... Next attempt:

```diff
diff --git a/default.nix b/default.nix
index 49c7c49..fc75259 100644
--- a/default.nix
+++ b/default.nix
@@ -74,13 +74,13 @@ let
         arpy = overrideWithSetuptools super.arpy { };
         yaffshiv = overrideWithSetuptools super.yaffshiv { };
         ubi-reader = overrideWithSetuptools super.ubi-reader { };
+        lief = overrideWithSetuptools super.lief { };
       });
 
     python = python3;
 
     postFixup = ''
       wrapProgram $out/bin/unblob --prefix PATH : ${lib.makeBinPath runtimeDeps} \
-                                  --set LOCALE_ARCHIVE_2_27 ${glibc}/lib/locale/locale-archive \
                                   --set LC_ALL C.UTF-8
     '';
 
```

I am not sure, if it compiles on mac, as the nixpkgs package for lief doesn't support darwin, but let's hope!

**Comment by daviewales** [comment]
That gets us further, but we need `cmake` to build the wheel. How do we add cmake into the lief build environment?

<details>

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/6j0kq3a4zn18ra9s62dgkz1ziyyain3r-lief-0.12.3.zip
source root is lief-0.12.3
setting SOURCE_DATE_EPOCH to timestamp 1667325146 of file lief-0.12.3/setup.cfg
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing pipBuildPhase
Creating a wheel...
[33mWARNING: The directory '/homeless-shelter/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.[0m[33m
[0mProcessing /private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/lief-0.12.3
  Running command python setup.py egg_info
  /private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/lief-0.12.3/setup.py:20: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    assert (LooseVersion(setuptools.__version__) >= LooseVersion(MIN_SETUPTOOLS_VERSION)), "LIEF requires a setuptools version '{}' or higher (pip install setuptools --upgrade)".format(MIN_SETUPTOOLS_VERSION)
  0.12.3
  running egg_info
  creating /private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/pip-pip-egg-info-x56v6wzi/lief.egg-info
  writing /private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/pip-pip-egg-info-x56v6wzi/lief.egg-info/PKG-INFO
  writing dependency_links to /private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/pip-pip-egg-info-x56v6wzi/lief.egg-info/dependency_links.txt
  writing top-level names to /private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/pip-pip-egg-info-x56v6wzi/lief.egg-info/top_level.txt
  writing manifest file '/private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/pip-pip-egg-info-x56v6wzi/lief.egg-info/SOURCES.txt'
  reading manifest file '/private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/pip-pip-egg-info-x56v6wzi/lief.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'api/python/build'
  warning: no previously-included files matching '*.so' found under directory '*.egg-info'
  adding license file 'LICENSE'
  writing manifest file '/private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/pip-pip-egg-info-x56v6wzi/lief.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... [?25l[?25hdone
Building wheels for collected packages: lief
  Running command python setup.py bdist_wheel
  /private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/lief-0.12.3/setup.py:20: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    assert (LooseVersion(setuptools.__version__) >= LooseVersion(MIN_SETUPTOOLS_VERSION)), "LIEF requires a setuptools version '{}' or higher (pip install setuptools --upgrade)".format(MIN_SETUPTOOLS_VERSION)
  0.12.3
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "/private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/lief-0.12.3/setup.py", line 92, in run
      subprocess.check_output(['cmake', '--version'])
    File "/nix/store/hp8vf91s8z2gljwdrf0i4jry8m3899m7-python3-3.10.7/lib/python3.10/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/nix/store/hp8vf91s8z2gljwdrf0i4jry8m3899m7-python3-3.10.7/lib/python3.10/subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/nix/store/hp8vf91s8z2gljwdrf0i4jry8m3899m7-python3-3.10.7/lib/python3.10/subprocess.py", line 969, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/nix/store/hp8vf91s8z2gljwdrf0i4jry8m3899m7-python3-3.10.7/lib/python3.10/subprocess.py", line 1845, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/lief-0.12.3/setup.py", line 484, in <module>
      setup(
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
      self.run_command(cmd)
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
      cmd_obj.run()
    File "/nix/store/vq5n2j2fy43n5gbhyp84ibxzd8lchzi2-python3.10-wheel-0.37.1/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
      self.distribution.run_command(command)
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
      cmd_obj.run()
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
      self.run_command(cmd_name)
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
      self.distribution.run_command(command)
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/nix/store/30rscxm2ia7dc37wkakln8g0s37iyk0p-python3.10-setuptools-65.3.0/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
      cmd_obj.run()
    File "/private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/lief-0.12.3/setup.py", line 94, in run
      raise RuntimeError("CMake must be installed to build the following extensions: " +
  RuntimeError: CMake must be installed to build the following extensions: lief
  [1;31merror[0m: [1msubprocess-exited-with-error[0m
  
  [31m×[0m [32mpython setup.py bdist_wheel[0m did not run successfully.
  [31m│[0m exit code: [1;36m1[0m
  [31m╰─>[0m See above for output.
  
  [1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
  [1;35mfull command[0m: [34m/nix/store/hp8vf91s8z2gljwdrf0i4jry8m3899m7-python3-3.10.7/bin/python3.10 -u -c '[0m
[34m  exec(compile('"'"''"'"''"'"'[0m
[34m  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py[0m
[34m  #[0m
[34m  # - It imports setuptools before invoking setup.py, to enable projects that directly[0m
[34m  #   import from `distutils.core` to work with newer packaging standards.[0m
[34m  # - It provides a clear error message when setuptools is not installed.[0m
[34m  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so[0m
[34m  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:[0m
[34m  #     manifest_maker: standard file '"'"'-c'"'"' not found".[0m
[34m  # - It generates a shim setup.py, for handling setup.cfg-only projects.[0m
[34m  import os, sys, tokenize[0m
[34m  [0m
[34m  try:[0m
[34m      import setuptools[0m
[34m  except ImportError as error:[0m
[34m      print([0m
[34m          "ERROR: Can not execute `setup.py` since setuptools is not available in "[0m
[34m          "the build environment.",[0m
[34m          file=sys.stderr,[0m
[34m      )[0m
[34m      sys.exit(1)[0m
[34m  [0m
[34m  __file__ = %r[0m
[34m  sys.argv[0] = __file__[0m
[34m  [0m
[34m  if os.path.exists(__file__):[0m
[34m      filename = __file__[0m
[34m      with tokenize.open(__file__) as f:[0m
[34m          setup_py_code = f.read()[0m
[34m  else:[0m
[34m      filename = "<auto-generated setuptools caller>"[0m
[34m      setup_py_code = "from setuptools import setup; setup()"[0m
[34m  [0m
[34m  exec(compile(setup_py_code, filename, "exec"))[0m
[34m  '"'"''"'"''"'"' % ('"'"'/private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/lief-0.12.3/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/pip-wheel-49d28d88[0m
  [1;35mcwd[0m: /private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/lief-0.12.3/
  Building wheel for lief (setup.py) ... [?25lerror
[31m  ERROR: Failed building wheel for lief[0m[31m
[0m[?25h  Running setup.py clean for lief
  Running command python setup.py clean
  /private/tmp/nix-build-python3.10-lief-0.12.3.drv-0/lief-0.12.3/setup.py:20: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    assert (LooseVersion(setuptools.__version__) >= LooseVersion(MIN_SETUPTOOLS_VERSION)), "LIEF requires a setuptools version '{}' or higher (pip install setuptools --upgrade)".format(MIN_SETUPTOOLS_VERSION)
  0.12.3
  running clean
  'build/lib.macosx-10.12-x86_64-cpython-310' does not exist -- can't clean it
  'build/bdist.macosx-10.12-x86_64' does not exist -- can't clean it
  'build/scripts-3.10' does not exist -- can't clean it
Failed to build lief
[31mERROR: Failed to build one or more wheels[0m[31m
[0m
```

</details>

**Comment by vlaci** [comment]
Maybe third time the charm:
```diff
diff --git a/default.nix b/default.nix
index 3e36008..0929bd8 100644
--- a/default.nix
+++ b/default.nix
@@ -1,7 +1,9 @@
 { lib
+, cmake
 , makeWrapper
 , mkPoetryApp
 , poetry2nix
 , glibc
 , python3
 , rustPlatform
@@ -75,14 +77,17 @@ let
         yaffshiv = overrideWithSetuptools super.yaffshiv { };
         ubi-reader = overrideWithSetuptools super.ubi-reader { };
         cairosvg = overrideWithSetuptools super.cairocffi { };
+        lief = overrideWithSetuptools (_: {
+          nativeBuildInputs = [ cmake ];
+        });
       });
 
     python = python3;
 
     postFixup = ''
       wrapProgram $out/bin/unblob --prefix PATH : ${lib.makeBinPath runtimeDeps} \
-                                  --set LOCALE_ARCHIVE_2_27 ${glibc}/lib/locale/locale-archive \
                                   --set LC_ALL C.UTF-8
     '';

```
